# Generated by Django 2.2.5 on 2021-04-14 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sispi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='domain',
            name='bottom_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='left_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='right_long',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domain',
            name='top_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='output',
            name='forecast',
            field=models.ManyToManyField(blank=True, null=True, related_name='outputs', to='sispi.Forecast'),
        ),
    ]
