# Generated by Django 2.2.5 on 2021-04-14 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sispi', '0002_auto_20210414_2227'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forecast',
            old_name='location',
            new_name='point',
        ),
    ]
