# Generated by Django 2.2.5 on 2021-04-15 03:13

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sispi', '0003_auto_20210414_2255'),
    ]

    operations = [
        migrations.RenameField(
            model_name='output',
            old_name='init_date',
            new_name='utc_init_date',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='forecast_hour',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='value',
        ),
        migrations.RemoveField(
            model_name='forecast',
            name='variable',
        ),
        migrations.AddField(
            model_name='forecast',
            name='forecast',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='forecast',
            name='v_lvl',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='output',
            name='hour',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pointlocation',
            name='ref',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
