# Generated by Django 2.2.5 on 2021-04-15 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sispi', '0004_auto_20210415_0313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metvariable',
            name='slug_name',
        ),
        migrations.AddField(
            model_name='metvariable',
            name='full_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metvariable',
            name='name',
            field=models.CharField(max_length=20),
        ),
    ]
